WEB ASG Team 3  (redo)/Controllers/SalesTransactionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB2022Apr_P02_T3.DAL;
using WEB2022Apr_P02_T3.Models;


namespace WEB2022Apr_P02_T3.Controllers
{
    public class SalesTransactionController : Controller
    {
        private SalesTransactionDAL salesTransactionContext = new SalesTransactionDAL();
        // GET: SalesTransaction
        public ActionResult Index(string? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) || 
                (HttpContext.Session.GetString("Role") != "Marketing"))
            {
                return RedirectToAction("Index", "Home");
            }
            CustomerViewModel custVM = new CustomerViewModel();
            custVM.customerList = salesTransactionContext.GetAllCustomers();

            if(id != null)
            {
                ViewData["selectedCustomer"] = id;
                custVM.salesTransactionList = salesTransactionContext.GetCustomerSalesTransaction(id);
            }
            else
            {
                ViewData["selectedCustomer"]  = "";
            }
            return View(custVM);
        }

        public ActionResult Rank(string? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
               (HttpContext.Session.GetString("Role") != "Marketing"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<TotalAmountViewModel> customerTotalAmountlist = salesTransactionContext.GetCustomerByTotalAmount();
            return View(customerTotalAmountlist);
        }

        // GET: SalesTransaction/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SalesTransaction/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SalesTransaction/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SalesTransaction/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SalesTransaction/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SalesTransaction/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SalesTransaction/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WEB ASG Team 3  (redo)/Views/SalesTransaction/Index.cshtml
@model WEB2022Apr_P02_T3.Models.CustomerViewModel

@{
    ViewData["Title"] = "Index";
}

<h4 class="PageTitle">View Transactions</h4>
<div>
    <a asp-action="Rank" asp-controller="SalesTransaction">Customers ranked by total transaction amount last month</a>
</div>
<!-- Display a list of customers -->
<div class="table-responsive">
    <table id="viewBranch" class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Gender</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.customerList)
            {
                string selectedRow = "";
                if (ViewData["selectedCustomer"].ToString()
                == item.MemberId.ToString())
                {
                    // Highlight the selected row
                    selectedRow = "class='table-primary'";
                }
                <tr @Html.Raw(selectedRow)>
                    <td>@item.MemberId.ToString()</td>
                    <td>@item.MName</td>
                    <td>@item.MGender</td>
                    <td>
                        <a asp-action="Index" asp-controller="SalesTransaction" asp-route-id="@item.MemberId">View Transactions</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<!-- Display a list of transactions for each customer -->
@if (ViewData["selectedCustomer"].ToString() != "")
{
    if (Model.salesTransactionList.Count != 0)
    {
        <h5>
            Transactions by customer
            @ViewData["selectedCustomer"].ToString() :
        </h5>
        <partial name="~/Views/SalesTransaction/_ViewTransaction.cshtml"
                 model="@Model.salesTransactionList" />
    }
    else
    {
        <h5>No staff for selected branch!</h5>
    }
}

WEB ASG Team 3  (redo)/Views/SalesTransaction/Rank.cshtml
@model IEnumerable<WEB2022Apr_P02_T3.Models.TotalAmountViewModel>

@{
    ViewData["Title"] = "Rank";
}

<h1>Rank</h1>

<h4 class="PageTitle">VIEW TRANSACTIONS</h4>
<!-- Add a partial view to display a list of staff records
in a tabular format. -->
<partial name="~/Views/SalesTransaction/_ViewCustomerByTransaction.cshtml" model="@Model" />
<div>
    <a asp-action="Index">Back to List</a>
</div>

WEB ASG Team 3  (redo)/Views/SalesTransaction/_ViewCustomer.cshtml
@model IEnumerable<WEB2022Apr_P02_T3.Models.Customer>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MemberId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MGender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MBirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MCountry)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MTelNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MEmailAddr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MPassword)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MemberId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MGender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MBirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MCountry)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MTelNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MEmailAddr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MPassword)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

WEB ASG Team 3  (redo)/Views/SalesTransaction/_ViewCustomerByTransaction.cshtml
@model IEnumerable<WEB2022Apr_P02_T3.Models.TotalAmountViewModel>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MemberID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalAmount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MemberID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalAmount)
            </td>
            <td>
                <a asp-action="Create" asp-controller="IssueVoucher"
                   asp-route-id="@item.MemberID" asp-route-amt="@item.TotalAmount" asp-route-date="@item.DateCreated" >Issue Voucher</a>
            </td>
        </tr>
}
    </tbody>
</table>

WEB ASG Team 3  (redo)/Views/SalesTransaction/_ViewTransaction.cshtml
@model IEnumerable<WEB2022Apr_P02_T3.Models.SalesTransaction>

<p>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.transactionID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.storeID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.memberID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.subtotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tax)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.discountPercent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.discountAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dateCreated)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.transactionID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.storeID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.memberID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.subtotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tax)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.discountPercent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.discountAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dateCreated)
            </td>
        </tr>
}
    </tbody>
</table>